### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by sheerun** [ruby-git/ruby-git#108]
@schacon How about maintenance status of this gem? There are many long lasted pull requests and issues. If you don't have time for it, maybe add some collaborator or transfer repo to different account?

**Comment by jantman** [comment]
Yes... it looks like this hasn't had a commit in over a year, and *this* issue is over 2 years old. If you're not intending on maintaining this, could you please make that clear in the README, and maybe look for a maintainer?
