### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by mrbrdo** [ruby-git/ruby-git#128]
There is an encoding issue with diffs. Note it might only be a problem on JRuby (I'm using 1.7.6). ruby-git will use IO.popen to run the git diff in this case.

I get the error when I am processing a repo that has the file `vendor/assets/javascripts/plupload-rails3/plupload/changelog.txt` and this file cannot be parsed (throws error in title).

The problematic line is this:

```
"+\tFixed so the runtime list can include whitespace or missing runtimes. Patch contributed by \xD8yvind Sean Kinsey.\r\n"
```

The character D8 is Ø in ISO-8859-1, but is invalid in UTF-8. It seems git is giving the output in ISO-8859-1 (or file itself is in this encoding) but IO.popen is tagging it as UTF-8. I'm not sure about that exactly. In either case, something must be done to at least get a string with such characters not displaying properly, but at least there should be no exception.

I have ideas on how to workaround it (in cache_full, check if valid_encoding, otherwise try latin1 and if that is also invalid then replace invalid sequences), but perhaps there is a proper solution, e.g. if git always gives text in latin1 it is possible to tell that to IO.popen and it will encode properly. I am not sure if the original file that was diffed had the wrong encoding and there is nothing we can do about it except replace the invalid char with the default replacement char (\uFFFD in utf-16le).

**Comment by Ekultek** [comment]
Hey, I just happened to stumble across this and have the same issue in one of my programs, did any of you by chance find a fix for it?
