### ISSUE TITLE
Support for GIT_SSH 

### ISSUE THREAD

**Issue by scottrobertson** [ruby-git/ruby-git#172]
Hey,

Awesome library!

One question, is there a way to use GIT_SSH so that we can specify a specific ssh key to use when cloning/pulling. See: http://stackoverflow.com/a/9321723/1296764

Thanks
Scott

**Comment by mikedillion** [comment]
I think there's a problem here. `GIT_SSH` tell's Git where it can find a wrapper script, not which key to use.

**Comment by robertodecurnex** [comment]
My bad. Even the tests are pending for that. Ty @mikedillion !
