### ISSUE TITLE
'old escape format for windows users' not working for jruby users on Windows

### ISSUE THREAD

**Issue by abltec** [ruby-git/ruby-git#179]
git Commands failing due to escaping.

git gem (1.2.8)
Code causing the problem:
lib/git/lib.rb
return "'#{s && s.to_s.gsub('\'','\'"\'"\'')}'" if RUBY_PLATFORM !~ /mingw|mswin/

I don't think you can rely on 'RUBY_PLATFORM' alone to detect OS as 
RUBY_PLATFORM equals "java" when using jruby.

**Comment by nnn-dev** [comment]
I have JRUBY 9.1.7.0 (ruby 2.x compatibily) and Windows 10.
I use the ENV ['OS'] to patch this issue.
On my machine ENV ['OS']='Windows_NT'.
