### ISSUE TITLE
`clone` does not use the logger

### ISSUE THREAD

**Issue by stgm** [ruby-git/ruby-git#208]
(Encountered when debugging #207).

The `Git.clone` call does not actually forward the logger to the `Lib` instance. A hackish way to solve this is included and documents the location of the problem:

```
module Git
    class Base
        def self.clone(repository, name, opts = {})
            # run git-clone 
            opts[:log] ||= nil
            self.new(Git::Lib.new(nil, opts[:log]).clone(repository, name, opts))
        end
    end
end
```

**Comment by mikeAtTealium** [comment]
I'm not sure why but this doesn't work for me.  If I figure out how to make it work, I'll post again

**Comment by mensfeld** [comment]
+1 still no logger...
