### ISSUE TITLE
Request: fake/test mode

### ISSUE THREAD

**Issue by cheshire137** [ruby-git/ruby-git#221]
I would love a fake/test mode for ruby-git, akin to [fog's](https://github.com/fog/fog) `Fog.mock!` or [Sidekiq's](https://github.com/mperham/sidekiq) `Sidekiq::Testing.fake!`. Ideally I could say something like `Git.fake!` to turn it on, then do clones and pulls and pushes and all the other commands, but they wouldn't actually run the commands or affect the file system. This would be very helpful for me to write tests for my code that uses ruby-git without actually cloning remote repositories or doing lengthy file system tasks.

**Comment by bilby91** [comment]
+1
