### ISSUE TITLE
Git error from log.object

### ISSUE THREAD

**Issue by cheshire137** [ruby-git/ruby-git#222]
I'm trying to do what is shown in the README, `@git.log(20).object("some_file").since("2 weeks ago").between('v2.6', 'v2.7').each { |commit| [block] }` but I get a Git error:

```
irb(main):011:0> Git.open(repo_path).log(2).object('post.html').each {|c| puts c }
Git::GitExecuteError: git '--git-dir=/path/to/my_repo/.git' '--work-tree=/path/to/my_repo' log '-2' '--no-color' '--pretty=raw' 'post.html'  2>&1:fatal: ambiguous argument 'post.html': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    from /var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command'
    from /var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:846:in `command_lines'
    from /var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:145:in `full_log_commits'
    from /var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/log.rb:119:in `run_log'
    from /var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/log.rb:112:in `check_log'
    from /var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/log.rb:84:in `each'
    from (irb):11
    from /var/lib/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/console.rb:90:in `start'
    from /var/lib/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/console.rb:9:in `start'
    from /var/lib/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:69:in `console'
    from /var/lib/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /var/lib/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
    from ./bin/rails:4:in `require'
    from ./bin/rails:4:in `<main>'
```

I'm using version 1.2.9.1 of the gem. The post.html file exists in the repository, but was not changed in the latest two commits that `log(2)` should be fetching. Am I using this wrong?

**Comment by moneypenny** [comment]
I'm using git version 1.9.1 in Linux. Maybe just add `--` before the file name?

**Comment by othatbrian** [comment]
I was able to reproduce the same error by using an incomplete path. Is your "post.html" inside a directory in the repo? If so, can you try specifying the path starting from the top of the repo?

**Comment by moneypenny** [comment]
No, post.html is in the root of the repository.

**Comment by othatbrian** [comment]
It appears that either the documentation is slightly wrong/misleading, or that the code has a bug; I'm honestly not sure which to consider it. If you change "object" to "path", it will work.

When you call the "path" method, the gem uses "--" in the native command to signify a path follows; if you use "object", it does not use "--" so the native command gets confused as to whether you're providing a path or a commit sha. The way the code reads, though, I'm not sure how an "object" would ever be useful in that context, as it's handled inside the log_path_options of Git::Lib.
