### ISSUE TITLE
Rebase and Cherry-pick commands

### ISSUE THREAD

**Issue by agargiulo** [ruby-git/ruby-git#223]
Is there a reason these two aren't included in this library? They would be very helpful, even if you don't use them all the time.

**Comment by agargiulo** [comment]
I saw someone started working on a rebase command in #101

**Comment by AnalogJ** [comment]
yea I'm looking for this as well

**Comment by kaldrenon** [comment]
+1

**Comment by victorgama** [comment]
+1 :+1:

**Comment by lucywyman** [comment]
+1

**Comment by zedtux** [comment]
Damned stupid bot. We are looking for this, stop clause human's issues. Reopen it immediately.

**Comment by cabello** [comment]
@EPecherkin @tarcinil would you accept a PR for rebasing?

**Comment by zedtux** [comment]
@cabello do you have a fork with the rebase command implemented please?

**Comment by cabello** [comment]
@zedtux we don't have any, we ended up using system commands for example:

```ruby
Dir.chdir(project_dir) do
  system("git remote add origin #{github_clone_url(repository_name)}")
  system("git checkout -b #{branch_name}")
  system("git add .")
  system("git commit -m \"Create #{name}\"")
  system("git push origin #{branch_name}")
end
```

**Comment by zedtux** [comment]
Make sense, thank you @cabello 👍
