### ISSUE TITLE
ruby-git status and command line git status differ 

### ISSUE THREAD

**Issue by josh803316** [ruby-git/ruby-git#23]
I'm attempting to check for git changes in a current directory after I re-write a file.  For some reason @git.status.changed always shows that the file has been changed, even though command line git status shows no diff, as it should.  Is there a way around this.  I'm attempting to decide whether to update a field in the file if it has been changed before pushing to git.

```
    # Check the if the contents of a directory in git
    def dir_has_changes? dir
        intersection = dir.split('/') - @top_level.split('/')
        intersection = intersection.join('/')
        has_changes = false
        @git.status.changed.each do |file|
            if file[0] =~ /#{intersection}/
                has_changes = true
            end
        end
        return has_changes
    end
```

**Comment by chilicheech** [comment]
This is affecting me as well. Why can't ruby-git `status` call `git status` instead of `git diff-files`? This implementation is confusing because it differs from `git`'s implementation.

**Comment by jon-rtr** [comment]
I'm running into the same behavior as listed above, so I would say this issue should be reopened.

> I'm having this issue as well.
> 
> EDIT
> 
> Curiously, shelling out to git status from ruby before, e.g. @git.status seems to result in the latter reporting status accurately.

I'm using `ruby-git 1.5.0` and `git version 2.15.2 (Apple Git-101.1)`.

**Comment by jon-rtr** [comment]
Running git diff-files on one of my repos, all of the files look like this:
```
$ git diff-files | head -n2
:100644 100644 51e14f30f818cde956880833f3c9a5822b54ad03 0000000000000000000000000000000000000000 M	.gitignore
:100644 100644 93deb154ae39ea2ae76c9a70ddf51be9dcbd8f4a 0000000000000000000000000000000000000000 M	README.md
```

**Comment by tarcinil** [comment]
@jon-rtr 

Thank you for your report.  As the issue is now seven years old and we can't be sure how the issue has changed over the many years.  Please create a new issue will all relevant data.
