### ISSUE TITLE
Git checkout doesn't track remote

### ISSUE THREAD

**Issue by BillyBarbaro** [ruby-git/ruby-git#239]
When checking out a new branch, you cannot set it to track the remote version of the branch.  I've forked the repo and added the --track option to the checkout method.  I plan to submit a pull request, but will wait a few days to make sure there's no additional functionality I may need to add.

**Comment by echernyavskiy** [comment]
Is there any update on this effort please? Would've been really useful.

Also, to accommodate repositories with multiple remotes, any chance you could add an option to specify the remote to checkout the branch from? I might have enough knowledge of Ruby to add the option myself but not to cover that with tests unfortunately.

**Comment by thierryxing** [comment]
Just fork and add --track option in [https://github.com/thierryxing/ruby-git](https://github.com/thierryxing/ruby-git)
