### ISSUE TITLE
Expanded Git::GitExecuteError?

### ISSUE THREAD

**Issue by olemd** [ruby-git/ruby-git#246]
It would be nice if GitExecuteError could keep hold of the command, the output and the exitstatus in separately accessible fields.

In particular, I have a program that attempts to do "git init; possibly-add-new-or-changed-files; git add .; git commit"

If no changes are actually present then commit will raise an error.

If I attempt "git init; possibly-add-new-or-changed-files; check-git-status-for-changes && (git add .; git commit)" then "git status" raises an error for new repositories.

Being able to catch a GitExecuteError and check what actually caused the error would be helpful.

**Comment by enekogb** [comment]
I will love to see this done (although the exit status code seems to be always "1"), so i can get a simple "nothing to commit, working directory clean" instead of this:

```
/git-1.5.0/lib/git/lib.rb:967:in `command': git '--git-dir=/tmp/git_20180917-80395-udixmb/.git' '--work-tree=/tmp/git_20180917-80395-udixmb' commit --all'  2>&1:# On branch 1537182636452 (Git::GitExecuteError)
nothing to commit, working directory clean
```
