### ISSUE TITLE
Git.clone does not allow passing in a logger

### ISSUE THREAD

**Issue by kevinrood** [ruby-git/ruby-git#28]
Maybe I'm missing something, but it seems like Git.clone should act like Git.open:

g = Git.clone (url, name, :log => Logger.new(STDOUT))

vs.

g = Git.open (working_dir, :log => Logger.new(STDOUT))

But it doesn't

**Comment by dstull** [comment]
yes - however, it is passing back a viable git object to be used for commits, adds, etc.  Can you suggest a workaround?
