### ISSUE TITLE
with_temp_working doesn't appear to do anything

### ISSUE THREAD

**Issue by jantman** [ruby-git/ruby-git#280]
I'm trying to use `.with_temp_working` but it doesn't appear to actually do anything.

If I have a small ruby script in a directory that's a git clone, and it does:

```
require 'git'
g = Git.open(Dir.pwd)
g.with_temp_working do
  g.checkout('mybranch')
end
```

When the script exits, I would expect my directory to be untouched, i.e. exactly as it was before. However, `pwd` seems to have had "mybranch" checked out.

As far as I can tell, `with_temp_working` is either completely unfinished, or I'm very confused about how it's supposed to work...

**Comment by robertodecurnex** [comment]
Hi Jason,

A couple of things to have in mind:

1. *Working Directory* != *Working Tree*
2. *git checkout branch_name* != *git checkout branch_name -- path_here*

From Git Commit Docs:

> If no paths are given, *git checkout* will also update HEAD to set the
> specified branch as the current branch.


So, checking out a branch will update the index reference, no matter wher
your current working directory is.

Checking out files is a different story.

You can try to play with *with_temp_index *in you want to leave the
original index untouched.

Regards,
--
Roberto Decurnex

**Comment by jantman** [comment]
Ok, thanks, sorry for my confusion. I'm still sort of unclear about what ``with_temp_working`` is supposed to __do__, but now I'm pretty clear it's not what I want.

Thanks. I'm working on an alternate solution to my problem now; I'll close this once I have it solved (and comment with a bit about what I was trying to do, and how I did it).
