### ISSUE TITLE
No way to determine the current branch the working directory is on?

### ISSUE THREAD

**Issue by theirishpenguin** [ruby-git/ruby-git#296]
I might have missed an obvious way to list the current branch in the readme.

Anyway, I have looked at...

https://github.com/schacon/ruby-git/blob/master/lib/git/branch.rb#L95

... but this returns a boolean, not a branch name.

For now I can workaround it with...

```
branch_name = git.branch.instance_variable_get(:@base).lib.branches_all.select { |b| b[1] }.first[0] rescue nil
```

... whereas

```
branch_name = git.branch.current
```

returns false.

I can see why, it is answering the question current? for a given branch name.

But how do I actually get the name of the current branch?

**Comment by greeneca** [comment]
Try:

https://github.com/schacon/ruby-git/blob/master/lib/git/base.rb#L534

or:

git.current_branch

**Comment by theirishpenguin** [comment]
Ah great. Thanks a mill, that worked.

Small PR to update the docs in case this helps someone else https://github.com/schacon/ruby-git/pull/298

**Comment by jonmchan** [comment]
:+1: I couldn't find out how to do it either and I had to comb through the code to find ```git.current_branch```. It'd be great to have it documented!

**Comment by OrangeCrush** [comment]
:+1: This issue helped me as well.  Maybe we could add as an example Thanks!

**Comment by fernandodev** [comment]
I think it should be closed.

**Comment by fernandodev** [comment]
I've created a section in the Wiki for it

https://github.com/schacon/ruby-git/wiki/Branches

**Comment by theirishpenguin** [comment]
Thanks @fernandodev. I don't think most people will read the wiki and they'd expect to see this in the README - along with all the other basic branch commands. Is there a reason that this shouldn't be added to the README?

**Comment by fernandodev** [comment]
@theirishpenguin  I can add in the README, but I do really want to improve this README et all ;) 
When I finish I tell you

**Comment by theirishpenguin** [comment]
Sounds great @fernandodev, thanks :-) :+1:
