### ISSUE TITLE
git clone within docker

### ISSUE THREAD

**Issue by nickwilmes** [ruby-git/ruby-git#305]
Hi,

I have been using this library for cloning a repo, adding a few files, and then committing those files.  It has worked great on my laptop, but as soon as I put it into a docker container it starts asking for a username and password.  Is it possible for me to give it the username and password within ruby?  I would like to avoid putting it as a system setting because I would like to have it change per request if possible.

**Comment by iabdulazeem** [comment]
Experiencing this same issue, can someone guide how to add credentials within ruby script so when we containerize it, it is able to access the remote repo?
