### ISSUE TITLE
failure if git not in path on "require 'git'"

### ISSUE THREAD

**Issue by greppy** [ruby-git/ruby-git#311]
If git is not in the path then "require 'git'" fails.

```
$ echo $PATH
/bin:usr/bin
```

```
$ ls -l ~/usr/local/bin/git
-rwxr-xr-x 117 USER GROUP 7837789 Oct 11 17:52 /home/USER/usr/local/bin/git*
```

```
$ ~/usr/local/bin/ruby -e "require 'git'"
/home/USER/usr/local/lib/ruby/gems/2.2.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git  version   2>&1:sh: git: command not found (Git::GitExecuteError)
        from /home/USER/usr/local/lib/ruby/gems/2.2.0/gems/git-1.3.0/lib/git/lib.rb:839:in `current_command_version'
        from /home/USER/usr/local/lib/ruby/gems/2.2.0/gems/git-1.3.0/lib/git/lib.rb:849:in `meets_required_version?'
        from /home/USER/usr/local/lib/ruby/gems/2.2.0/gems/git-1.3.0/lib/git.rb:25:in `<top (required)>'
        from /home/USER/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /home/USER/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /home/USER/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from -e:1:in `<main>'
```

It looks like this is due to the version check at the top of lib/git.rb, at line 25, the Git.configure can be parsed.

```
lib = Git::Lib.new(nil, nil)
unless lib.meets_required_version?
  $stderr.puts "[WARNING] The git gem requires git #{lib.required_command_version.join('.')} or later, but only found #{lib.current_command_version.join('.')}. You should probably upgrade."
end
```

**Comment by jordansissel** [comment]
I see this was closed as stale, but an fpm user ran into this problem today. Can it be reopened?

https://github.com/jordansissel/fpm/issues/1748

**Comment by jcouball** [comment]
Sounds like a problem that we should solve.  Thanks, @jordansissel

**Comment by jordansissel** [comment]
Any thoughts on a preferred solution? 

One idea: Move this check into Git::Lib#command (with caching of result), this way the `git` library can be loaded and used, and exceptions for a missing or unsupported git are thrown only when the `git` command is invoked? 
This may have implication for users since the supported-git-version check would move much deeper and users of this library may find surprise at a new location where this exception is moved?

Bonus idea (scope creep? 🤷): If `git` binary is not found, emit an exception specific to that.

**Comment by jcouball** [comment]
I haven't really looked into the problem so I don't have any opinions on how to solve this problem yet.

However, sounds like we agree on requirements for the behavior when the git binary can not be found:
1. requiring the 'git' gem should not raise an error
2. an error should be raised as late as possible: when the git command is actually needed
3. the exception raised should be specific to the fact that the git binary was not found

**Comment by jcouball** [comment]
I haven't really looked into the problem so I don't have any opinions on how to solve this problem yet.

However, sounds like we agree on requirements on the behavior when the git binary can not be found:
1. requiring the 'git' gem should not raise an error
2. an error should be raised as late as possible: when the git command is actually needed
3. the exception raised should be specific to the fact that the git binary was not found

**Comment by Git-me-outta-here** [comment]
I had this today in a docker container, solved it by adding `git`

`RUN apt-get install -y ruby ruby-dev rubygems build-essential git`

**Comment by jcouball** [comment]
This no longer seems to be a problem. An error is no longer reported:

```shell
$ ruby -e "require 'git'"
$
```
