### ISSUE TITLE
Stashes API leaks a file handle

### ISSUE THREAD

**Issue by coderanger** [ruby-git/ruby-git#312]
The stashes API doesn't make sure to close the file handle to `log/refs/stash` which can mean it is held open, which on Windows can make it impossible to delete the repo.

**Comment by coderanger** [comment]
The relevant code hasn't change I don't think, https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L602

That just needs to get moved to a block form.

**Comment by coderanger** [comment]
Still a bug AFAIK.

**Comment by tarcinil** [comment]
@coderanger 

I will look into it. 

To verify based on time drift, the line in question is now.

https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L605

**Comment by coderanger** [comment]
Yep, that should be more like:

```ruby
File.open(filename) do |f|
  f.each_with_index do |line, i|
          m = line.match(/:(.*)$/)
          arr << [i, m[1].strip]
    end
end
```

**Comment by perlun** [comment]
@coderanger Sorry for the spam from our bots. 😉 The idea is to get rid of inactive issues where the original requester is no longer participating in the discussion/issues that might have been resolved/issues where no-one cares about the resolution any more. The "pinned" label can be applied by the contributors to flag an issue for "do not close automatically".
