### ISSUE TITLE
jruby tests are very flaky

### ISSUE THREAD

**Issue by kamaradclimber** [ruby-git/ruby-git#319]
While trying to make test pass for #318, I've noticed that jruby tests are really flaky.

See https://travis-ci.org/schacon/ruby-git/builds/182204463, https://travis-ci.org/schacon/ruby-git/builds/182015600 and https://travis-ci.org/schacon/ruby-git/builds/182011837 (virtually same code).

This makes contribution hard to tests.

**Comment by perlun** [comment]
I _think_ this is the same as I just saw: https://travis-ci.org/ruby-git/ruby-git/jobs/350814139

We should look into sorting this out, or disabling these tests on JRuby (if all else fails.)

**Comment by jcouball** [comment]
I believe this was fixed in #403 and released in [v1.6.0.pre1](https://github.com/ruby-git/ruby-git/releases/tag/v1.6.0.pre1)
