### ISSUE TITLE
Diff renamed files?

### ISSUE THREAD

**Issue by daniel-beard** [ruby-git/ruby-git#328]
I've been trying to get the list of files that have been renamed from a particular diff.
I can see that I get at least get the SHAs for the `src` and `dst` of a particular `DiffFile`.

Ideally I'd want the `process_full_diff` method inside `diff.rb`:
```
          if m = /^diff --git a\/(.*?) b\/(.*?)/.match(line)
            current_file = m[1]
            final[current_file] = defaults.merge({:patch => line, :path => current_file})
          else
```
to also include the second capture and expose these properties as `src_file_path` and `dst_file_path`.
Is there something I'm missing? 
Is there an easier way to do this today?

**Comment by daniel-beard** [comment]
I suppose I could match each line of the diff, but it'd be nice to have built-in support for this.

**Comment by Martoon-00** [comment]
Also vote for this issue, both old and new filepaths must be exposed.

**Comment by yakimant** [comment]
Old, closed, but still missing.

Maybe using `--no-renames` option could be added?
