### ISSUE TITLE
Crash if log contains foreign characters(?)

### ISSUE THREAD

**Issue by fwal** [ruby-git/ruby-git#33]
Hi!

I'm running version 1.2.5 of the gem and 1.9.2 (p290) of ruby.
The following code crashes if the log contains a foreign character in the git log:

``` ruby
require 'git'

# Init git and get log
g = Git.init
log = g.log

changelog = "My changes: \n"

# Now create changelog (and crash)
log.each {|l| 
   changelog += "- " + l.message + "\n")
}


```

Stack trace:

```
[...]/gems/git-1.2.5/lib/git/lib.rb:672:in `split': invalid byte sequence in US-ASCII (ArgumentError)
   from [...]/gems/git-1.2.5/lib/git/lib.rb:672:in `command_lines'
   from [...]/gems/git-1.2.5/lib/git/lib.rb:92:in `full_log_commits'
   from [...]/gems/git-1.2.5/lib/git/log.rb:108:in `run_log'
   from [...]/gems/git-1.2.5/lib/git/log.rb:101:in `check_log'
   from [...]/gems/git-1.2.5/lib/git/log.rb:84:in `each'
   from gittest:10:in `<main>'
```

Any ideas?

**Comment by fwal** [comment]
Seems abandoned 🗑

**Comment by ut** [comment]
Looking at the queue of the waiting PR, that's a pity.

**Comment by rvodden** [comment]
Myself at @perlun are in the process of resurrecting the project. I don't want this issue to get lost so I'm re-openong. We've not discussed priorities yet, however internationalization is likely to be high.

**Comment by ut** [comment]
It seems that this issue has been solved in the meantime. I succesfully checked it with the example provided by @fwal

**Comment by fwal** [comment]
That's awesome @ut, then I'll close this for real 🎉
