### ISSUE TITLE
Could not get current working directory in Git.clone

### ISSUE THREAD

**Issue by surajhell88** [ruby-git/ruby-git#330]
I clone repository using 
`Git.clone(<git-repo-url>, <directory-name>, path: <workspace-directory-path>)`

Most of the time above code successfully clones the repo but sometimes it throws following error

```
Git::GitExecuteError: 
git  clone '--' 'git@github.com:<username>/<repository-name>.git' '<workspace-directory-path>/<directory-name>'  2>&1:fatal: Could not get current working directory: No such file or directory
  from git/lib.rb:937:in `command'
  from git/lib.rb:76:in `clone'
  from git/base.rb:29:in `clone'
  from git.rb:97:in `clone'
```

Can't understand why. Tried debugging it but with no success. Posting it here if in case anyone could help.

**Comment by tosmi** [comment]
what is your current working directory? maybe the directory where you are executing the command got removed...

**Comment by surajhell88** [comment]
So to give you an idea, I built a Ruby gem which works as a CLI to clone repositories. I have crossed check if that directory got removed but it wasn't. Kind of weird behavior, it works most of the time but sometimes it gives me this error.
