### ISSUE TITLE
MAINTENANCE: move to organization account, add more maintainers

### ISSUE THREAD

**Issue by perlun** [ruby-git/ruby-git#334]
Hi everybody,

As can be seen on GitHub, it's quite evident that the current state of the project is sub-par. With 84 open pull requests, I get the feeling that the current maintainer(s) do not have enough time to devote to the project to give it the ❤️ it needs.

This is no strange thing at all; in fact I think it's very common with FOSS projects. Initially, you have time to devote to it, but as time goes, other things tend to get more of your attention (like: other projects, family, non-computer-related activites, etc).

@schacon and @robertodecurnex, I admire the great work that you and many, many others have done during the past.

Would you be open to move the project to an organization account (https://github.com/ruby-git that I just created)? It then makes it more clear that this is a "community project" and not something personally owned by an individual. We did the same thing with [rack-test](https://github.com/rack-test/rack-test) a while ago, where the project was in a very similar shape (the original maintainer didn't have time to devote to the project, other people were willing to step in).

We can then work together to try and get the project into a better shape. (Note: I don't personally have very much time to devote to it either, I'm more just "helping it happen" and can devote a few minutes here and there.)

If other people are willing to contribute time, **please note it here** as well! I think especially people who have contributed to this project in the past would be very interesting, but also people who have done quality contributions to other Ruby-related projects in the past would also be very welcome from my POV.

**Comment by perlun** [comment]
Emailed Scott today, let's see if we can get this one moving in a good direction.

**Comment by perlun** [comment]
The repo has now been moved to the new address: https://github.com/ruby-git/ruby-git/, and I have been granted access to it also. Thank you for this, @schacon!

I don't have that much time available at the moment for going through bugs etc, so if we have volunteers available who would be willing to step up, **please sign up** and help us make ruby-git an even better gem than it currently is. The comment field below is where you enroll. 😉

**Comment by rvodden** [comment]
Very happy to help. I'll head over to the new repo and see what needs to be done. I guess step one is porting over all the outstanding pull requests...

**Comment by perlun** [comment]
@rvodden Glad to hear! I sent you an invite now, please accept it and you should be able to start digging in.

I enabled Travis runs again (they have been defunct for some time) and made that a requirement before merging, to reduce the risk that we mess something up by mistake.

**Comment by rvodden** [comment]
Great! I'll spin up a github project so we can prioritize our work. Then I'll start at the back and get some of the high value PRs merged in.

**Comment by rvodden** [comment]
@perlun I've pinged you an access request for Scrutinizer - it gives us some pretty cool static code inspection capabilities which will let us track our tech debt. Can you approve please? :-)

**Comment by perlun** [comment]
@rvodden Sure, let's give it a try. I approved it now.

**Comment by perlun** [comment]
This has now been accomplished. Closing issue.
