### ISSUE TITLE
RubyGems.org points at old repository

### ISSUE THREAD

**Issue by rvodden** [ruby-git/ruby-git#341]
Given I visit https://rubygems.org/gems/git
When I press the 'Source Code' link
I expect to be taken to 'https://github.com/ruby-git/ruby-git/'
I am actually taken to 'https://github.com/schacon/ruby-git'

Similar applies to the home page.

**Comment by rvodden** [comment]
@perlun I've spun this issue up so we can talk about release strategy. I can see two approaches. Either we release a 1.3.1 which does nothing other than update all the links to point at this repository, and then crack on with merging and fixing and aim for a 1.4. Or we forget 1.3.1 and wait to update the links with the substantial changes which 1.4 will bring.

**Comment by perlun** [comment]
@rvodden Given that the project has been stale for so long, I think a 1.3.1 (with fixed links) would make sense.

@schacon If you could add me and @rvodden on Rubygems.org also, that would be great. My Rubygems user name is (unsurprisingly) `perlun`.

**Comment by rvodden** [comment]
@schacon, any news? I'm reluctant to start putting effort into this until we know we can publish.

**Comment by schacon** [comment]
Done, added Per to the gem. Sorry about the delay.

**Comment by perlun** [comment]
Thanks @schacon! @rvodden, I've verified that I have access so I can publish a version once you feel we are ready. I can probably also add you as a maintainer if/when needed.

**Comment by perlun** [comment]
@rvodden I fixed Travis so we can now be happy (happier.) If/when you have fixed the Rubygems reference, let me know and I can put out a 1.3.1 release.

I will then move on to prepare for a 2.0 release, where we drop support for EOL versions of JRuby and JRuby. This means 2.2 (EOL 2018-03-31), 2.3, 2.4 and 2.5, and JRuby 9k. I want to make it explicit and use a new major version for that, in line with the SemVer philosophy - no other major changes are planned at the moment.

**Comment by perlun** [comment]
@rvodden Will you have a chance to look into this?

**Comment by rvodden** [comment]
Yeah - expect something Saturday morning.

**Comment by perlun** [comment]
I've released a 1.4.0 version now, full details here: https://github.com/ruby-git/ruby-git/releases/tag/v1.4.0 🎉 

(The home page URL at https://rubygems.org/gems/git still refers to the old schacon URL, but I guess it's just cached.)

Thanks @rvodden, @dpmex4527 and others for helping this happen! 👍
