### ISSUE TITLE
Git commands should not all be chomped by default

### ISSUE THREAD

**Issue by dhollinger** [ruby-git/ruby-git#347]
Not all git subcommand output should be chomped by default. 

For example, `git show` should never have its results chomped because when it does it does actually return different content AND a different MD5 Sum hash than what is actually stored in the git repository.

This is incredibly important for automation and config management systems that rely on the results of a `git show` to determine if file contents on disk have changed or not. Even though this is potentially an outlier use case, the fact remains that the content of a file pulled from a git commit should _NEVER_ be munged, chomped, or modified in any other way that will return different content than what is actually stored in the git commit.

**Comment by dhollinger** [comment]
@perlun or anyone else.

Are there any plans to address this issue?

**Comment by perlun** [comment]
@dhollinger I agree from reading the issue now - like you say, it should be addressed. If you don't mind, please submit a PR and I'll happily look at it.

**Comment by dhollinger** [comment]
@perlun I'll take a look at it over the weekend and see what I can come up with.
