### ISSUE TITLE
JRuby build is intermittently failing

### ISSUE THREAD

**Issue by rvodden** [ruby-git/ruby-git#358]
From @perlun 

> I think the root cause here is that our code is not really thread safe, and that's why JRuby (which is much more concurrent than the evil-GIL-threaded MRI) triggers these errors.
> [..]
> The error:
> 
> Error: test_git_init_bare(TestThreadSafety): Git::GitExecuteError: git '--git-dir=/tmp/d20180328-6779-88i76v/.git' init '--bare'  2>&1:fatal: GIT_WORK_TREE (or --work-tree=<directory>) not allowed without specifying GIT_DIR (or --git-dir=<directory>)
> ...indicates that something goes wrong; it does specify the --git-dir but git still complains about this.
> 
> I read[ this SO thread](https://stackoverflow.com/questions/25172470/git-error-fatal-git-work-tree-or-work-tree-directory-not-allowed-without) but I couldn't see the GIT_WORK_TREE variable being set on the Travis machines.

**Comment by jcouball** [comment]
I believe this was fixed in #403 and released in [v1.6.0.pre1](https://github.com/ruby-git/ruby-git/releases/tag/v1.6.0.pre1)
