### ISSUE TITLE
Documentation: How to checkout remote branch

### ISSUE THREAD

**Issue by sumdog** [ruby-git/ruby-git#359]
I'm having the same issue listed in #337, and it was closed without a solution being given. I've also tried the following:

    git = Git.clone('https://github.com/foo/bar/', '.', :path => '/tmp/a')
    git.remote.branch('somebranch').checkout

..and ruby-git still just makes a new local branch instead of checkout out the remote one. Could we get some documentation added to the readme on how to checkout a remote branch?

**Comment by danielserrao** [comment]
The way I checkout the remote branch (for example with branch master and remote origin) successfully is:

```
g = Git.open("/path/to/repo")
g.checkout('master')
g.pull('origin','master')
```

Give it a try.
