### ISSUE TITLE
Document How to Use git.status

### ISSUE THREAD

**Issue by orarnon** [ruby-git/ruby-git#393]
### Subject of the issue
Got the following error after upgrading git:
irb(main):012:0> g.status.changed.size
Git::GitExecuteError: git '--git-dir=/Users/or.a/git/chef/.git' '--work-tree=/Users/or.a/git/chef' ls-files '--stage' ''  2>&1:fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/lib.rb:861:in `command_lines'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/lib.rb:400:in `ls_files'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/status.rb:88:in `construct_status'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/status.rb:8:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/base/factory.rb:63:in `new'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/git-1.3.0/lib/git/base/factory.rb:63:in `status'
	from (irb):12
	from /opt/chefdk/embedded/bin/irb:11:in `<main>'

### Your environment
* version of git and ruby-git
git: stable 2.19.1 (via brew)
git gem: 1.3.0
* version of ruby
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Looking for the correct syntax to resolve the empty pathspec issue.

### Actual behaviour
What actually happened?

**Comment by sudizhe** [comment]
Seems to be an issue with versions of git after 2.15

I fixed it by changing line 398 of lib.rb from:
```
def ls_files(location=nil)
```
to:
```
def ls_files(location='.')
```

**Comment by orarnon** [comment]
@sudizhe Did you manage to work around it without the lib change? I could not find a way to provide a location.
