### ISSUE TITLE
how to `set-upstream-to` in a branch?

### ISSUE THREAD

**Issue by rpbaltazar** [ruby-git/ruby-git#394]
### Subject of the issue

I've been looking around and fiddling with the codebase to try to understand how could i set-upstream-to in a branch and I can't seem to figure out a way of doing so. Does this library support such thing?

### Your environment
* git version: 2.19.0
* ruby-git version: 1.4.0
* ruby version: 2.3.1

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
What did you expect to happen?

### Actual behaviour
What actually happened?

**Comment by domi91c** [comment]
I'm trying to figure this out as well. Couldn't do it without a monkey-patch.

**Comment by stamizharasu** [comment]
Did anyone figure this out?

**Comment by jeremiegalante** [comment]
I was facing the same problem and I choosed another way to get over this and also other missing commands.

1. Create a monkey patch that maps a GitBase method to call a full git command

```
class Git::Base
  def cmd(cmd); self.lib.cmd(cmd); end
end
```

2. Create another monkey patch into the Git::Lib that is a path through to the private git command execution

```
class Git::Lib
  def cmd(cmd); command(cmd); end
end
```

3. Then you should be able to execute any git command like so : `git.cmd('branch -u origin/my_local_branch')`

**Comment by Bluelich** [comment]
@jeremiegalante  
I followed this patch，but got error below， while it worked well when I run the command in the terminal。
```output: "git: 'branch -u origin/feature/1.1.0' is not a git command. See 'git --help'.\n"```

ENV 
```
macOS Ventura 13.5.1 
ruby-git 1.18.0
git 2.39.2
```
