### ISSUE TITLE
Can't access private repos?

### ISSUE THREAD

**Issue by ChristofferJoergensen** [ruby-git/ruby-git#421]
According to [the docs](https://github.com/ruby-git/ruby-git#examples) I can add a custom SSH script like this:

```ruby
require 'git'
Git.configure do |config|
  # If you need to use a custom SSH script
  config.git_ssh = '/path/to/ssh/script'
end
```

I can't find any examples of such a custom script. I have tried to just insert the path to my SSH key:

    '/Users/my-user/.ssh/id_rsa'

But when trying to interact with the private repo I am prompted and expected to type a password. So clearly the path I have inserted is not what was expected.

I'm using MacOs Sierra and git 1.5.0.

Anyone who can help me?

**Comment by Winterspite** [comment]
Here's a good example of using custom scripts:

https://stackoverflow.com/a/14221028
