### ISSUE TITLE
status untracked returns all files when ruby working directory is not same as git repo root

### ISSUE THREAD

**Issue by asymptotik** [ruby-git/ruby-git#422]
### Subject of the issue
I was attempting to use ruby_git in fastlane which runs with the working directory under <repo root>/fastlane. When attempting the following code, I get all the files:

```
require 'git'

git = Git.open('../')

p 'Untracked: '
git.status.untracked.each { |s| 
  p "#{s.to_s}" if s[1].untracked
}
```
If I run that some code in my repo root except with `git = Git.open('../')` I get the expected results which is just the files that are untracked. 

### Your environment
git version 2.18.0
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
I expected my program to exhibit the same results no matter where it is run provided that Git.open is passed the proper path to the repository root.

### Actual behaviour
See above.

**Comment by jelaniwoods** [comment]
@asymptotik This might be relevant https://github.com/ruby-git/ruby-git/issues/23#issuecomment-58932274

**Comment by jcouball** [comment]
I will have to reimplement how Git::Base#status fetches untracked files to actually use `git status`. I am afraid this will stay one the back burner for a bit longer.
