### ISSUE TITLE
Pull without args results in unexpected operation

### ISSUE THREAD

**Issue by hlascelles** [ruby-git/ruby-git#423]
### git.pull should do what `git pull` does, but it doesn't

There are a couple of [other issues](https://github.com/ruby-git/ruby-git/issues/32) in this repo around pull/fetch, but I'm not sure they are the same as this one.

Consider the following code:

```
git.checkout("foo")
git.pull
```

You'd think it would do the same as this, but it doesn't.

```
git checkout "foo"
git pull
```

You must do:

```
branch = "foo"
git.checkout(branch)
git.pull("origin", branch)
```

We find this quite unexpected. Is there a rationale for it?

**Comment by hlascelles** [comment]
This is still an issue. A week over Christmas was not enough to react! I will (re)open.

**Comment by hlascelles** [comment]
Still an issue.

@perlun I feel the way the gem works now is "unexpected", and breaks [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Would you accept a PR to change it?

**Comment by jcouball** [comment]
@hlascelles I agree with your assessment.

Since this change would break backwards compatibility, it would have to be targeted to the next major release.

**Comment by hlascelles** [comment]
Sounds good. (Also, remove the `wontfix` label. Thanks!)

**Comment by hlascelles** [comment]
@jcouball can this be marked with Milestone 2.0, and stalebot be configured to ignore future milestones (ot some similar config?).

**Comment by jcouball** [comment]
I am considering this a bug and not a feature change so will include the fix for it into the next release.
