### ISSUE TITLE
git cherry

### ISSUE THREAD

**Issue by europ** [ruby-git/ruby-git#428]
### Subject
Implementation of the [`git cherry`](https://git-scm.com/docs/git-cherry) is missing.

A closed PR https://github.com/ruby-git/ruby-git/pull/97 implementing this command was closed (it was close by stale bot).

### Environment
* version of ruby-git: [1.5.0](https://github.com/ruby-git/ruby-git/releases/tag/v1.5.0)
* version of ruby: 2.6.4
* version of git: 2.21.0
* operating system: Fedora 30

### Expected behaviour
`master` branch includes the following commits: (A)-(B)-(C), where (A) is root and (C) is HEAD.

`feature` branch is created from master and includes two newly added commits: master-(D)-(E), where (E) is the HEAD of the `feature` branch.

Command cherry(`master`, `feature`) should return the two newly added commits (D)-(E).

For further details please see https://git-scm.com/docs/git-cherry

### Actual behaviour
Not supported yet in the latest release.

**Comment by europ** [comment]
ping @rvodden @perlun @tarcinil

**Comment by jcouball** [comment]
`Git::Log#cherry` was added in #97 which is part of the [v1.8.0](https://github.com/ruby-git/ruby-git/releases/tag/v1.8.0) release.
