### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by hlascelles** [ruby-git/ruby-git#432]
Can we get a project status update?

Essentially all issues that I can see that have been raised since 2018 have been marked stale and closed by the stalebot very soon afterwards without comment from project owners.

I'm not saying all issues have to be worked on, this is open source and we can contribute, but are there active maintainers that can comment on issues and indicate that a PR would be well received?
(Even then, [valid PRs](https://github.com/ruby-git/ruby-git/pull/420) are being ignored and closed by the stalebot).

At the very least can we disable the stalebot?

**Comment by hlascelles** [comment]
@jcouball, @perlun or @tarcinil are any of you maintainers?

**Comment by perlun** [comment]
Yes, I am a (too passive) maintainer. My main problem is that I am not using the gem any more after switching jobs; I'm hardly even using Ruby at all. So there is very little incentive from my end to spend time on the project, regretfully.

@jcouball have been lending a helping hand lately; thanks a lot for this.

I will try to get a version 1.6.0 released later this week. But in the long run, we should clearly try to get more active people helping out with maintaining this gem. Especially useful would be to get people in who are using it in their work, where one or more work projects depend on the gem for its functionality.

**Comment by jcouball** [comment]
Thanks, Per.  I will be spending more time on this.  If you'd like I can try to get this release out with the notes you sent me.
James.
    On Tuesday, January 14, 2020, 12:20:34 PM PST, Per Lundberg <notifications@github.com> wrote:  
 
 
Yes, I am a (too passive) maintainer. My main problem is that I am not using the gem any more after switching jobs; I'm hardly even using Ruby at all. So there is very little incentive from my end to spend time on the project, regretfully.

@jcouball have been lending a helping hand lately; thanks a lot for this.

I will try to get a version 1.6.0 released later this week. But in the long run, we should clearly try to get more active people helping out with maintaining this gem. Especially useful would be to get people in who are using it in their work, where one or more work projects depend on the gem for its functionality.

**Comment by perlun** [comment]
@jcouball 

> Thanks, Per.  I will be spending more time on this.  If you'd like I can try to get this release out with the notes you sent me.

That's not a bad idea at all actually! If you create a Rubygems account and PM/email me your username, I'll try to grant you the privileges required to push the version to https://rubygems.org/gems/git.

Given that this is a project with multi-million downloads (8 millions for version 1.5.0 alone), would it make sense to perhaps push it as a `1.6.0.pre` version first? Just to minimize the risks if we (by accident) have merged something not yet fully ready to be deployed to the masses. :slightly_smiling_face:

**Comment by perlun** [comment]
@hlascelles 

> At the very least can we disable the stalebot?

PR done - #433.

**Comment by jcouball** [comment]
My RubyGems username is 'jcouball'.
I'll update the version to 1.6.0.pre sometime today.
James.
    On Friday, January 17, 2020, 05:07:11 AM PST, Per Lundberg <notifications@github.com> wrote:  
 
 
@jcouball


Thanks, Per. I will be spending more time on this. If you'd like I can try to get this release out with the notes you sent me.


That's not a bad idea at all actually! If you create a Rubygems account and PM/email me your username, I'll try to grant you the privileges required to push the version to https://rubygems.org/gems/git.

Given that this is a project with multi-million downloads (8 millions for version 1.5.0 alone), would it make sense to perhaps push it as a 1.6.0.pre version first? Just to minimize the risks if we (by accident) have merged something not yet fully ready to be deployed to the masses. 🙂

**Comment by jcouball** [comment]
Per, 
Do you have advice for how to announce 1.6.0 release and how we should schedule future releases?
James.
    On Friday, January 17, 2020, 05:07:11 AM PST, Per Lundberg <notifications@github.com> wrote:  
 
 
@jcouball


Thanks, Per. I will be spending more time on this. If you'd like I can try to get this release out with the notes you sent me.


That's not a bad idea at all actually! If you create a Rubygems account and PM/email me your username, I'll try to grant you the privileges required to push the version to https://rubygems.org/gems/git.

Given that this is a project with multi-million downloads (8 millions for version 1.5.0 alone), would it make sense to perhaps push it as a 1.6.0.pre version first? Just to minimize the risks if we (by accident) have merged something not yet fully ready to be deployed to the masses. 🙂

**Comment by perlun** [comment]
> My RubyGems username is 'jcouball'. I'll update the version to 1.6.0.pre sometime today.

Great! I added you as an owner of the gem now, so you can publish new versions also.

As for announcing new versions: I don't know of a perfect scheme here. Go with whatever you think works best. :slightly_smiling_face: It's probably best to release reasonably often, ideally once a month or once a quarter or something. WDYT?

The releases don't have to be pre-announced I think, people will notice them anyway. :wink:

**Comment by jcouball** [comment]
@hlascelles, thank you for raising this issue.  I created issue #434 to create the 1.6.0 release so we have a starting point to kick off accepting the backlog of great PRs.  I have committed time to be a more active maintainer and will begin PR reviews as soon as the changes for a 1.6.0 release have been merged to master.

Is there anything else you wanted to see happen with this issue?  If not, please close it.

**Comment by hlascelles** [comment]
All good, thank you for getting everything moving! 

I was going to ask if dropped issues could be reopened (including [mine](https://github.com/ruby-git/ruby-git/issues/423) :slightly_smiling_face:), but that might be an avalanche. I'll leave that up to you.

Looking forward to the new releases, will help where I can. :+1:
