### ISSUE TITLE
Create the 1.6.0 release

### ISSUE THREAD

**Issue by jcouball** [ruby-git/ruby-git#434]
### Subject of the issue
Create the 1.6.0 release, the first release since August 18th, 2018.

Since it has been so long, the maintainers have decided to create a pre-release (1.6.0.pre1) with the pending changes.  The maintainers will need to determine criteria for releasing a proper 1.6.0 release and put it in this issue so that people will know what to expect.

**Comment by jcouball** [comment]
@perlun 

Prerelease 1.6.0.pre1 was released and pushed to rubygems.org

See https://github.com/ruby-git/ruby-git/releases/tag/v1.6.0.pre1

How does it sound to push a real 1.6.0 release in a week on Monday, Jan 27th?

**Comment by perlun** [comment]
👍🏻 Works for me

**Comment by TLiu2121999** [comment]
any updates? isn't it scheduled on Jan 27?

**Comment by perlun** [comment]
Ping @jcouball :slightly_smiling_face:

**Comment by jcouball** [comment]
Thank you @TLiu2121999 for the reminder to give an update here.

This week, I have been working through issue #418 because I wanted to make sure it wasn't caused by #405 (a new change introduced in 1.6.0.pre1).  I believe that we have decided that it was not caused by #405 so I believe we are good to go with a new release.  I will get to it as soon as possible.

FWIW, the fix for #418 is a WIP in #440.

**Comment by jcouball** [comment]
Created PR #443 for Release v1.6.0

**Comment by jcouball** [comment]
[The git gem version v1.6.0](https://github.com/ruby-git/ruby-git/releases/tag/v1.6.0) has been released!
