### ISSUE TITLE
Streaming stdout instead of one response

### ISSUE THREAD

**Issue by aquaflamingo** [ruby-git/ruby-git#441]
### Subject of the issue
Hi there, :wave: great library. 

For long running git operations, I'm wonder the thoughts on adding a "stream stdout" option to the library instead of the [current](https://github.com/ruby-git/ruby-git/blob/f5cd6a62d3d5b9f716d1814eb74159bf2679b25c/lib/git/lib.rb#L963) implementation which takes the bulk response back stores it in a variable and returns it.

Is this something you think would be relatively simple and / or desirable?

**Comment by jcouball** [comment]
#617 should enable doing this. It isn't possible with the current way that the library calls `git` with backticks.

**Comment by jcouball** [comment]
Fixed with #684 and released in [git-2.0.0-pre1](https://rubygems.org/gems/git/versions/2.0.0.pre1)
