### ISSUE TITLE
Tarballs ship (bare) git repo tests/files/working.git

### ISSUE THREAD

**Issue by dleidert** [ruby-git/ruby-git#464]
Hi there,

the source tarballs contain a very old copy of a git repository in [`tests/files`](https://github.com/ruby-git/ruby-git/tree/master/tests/files). Is this supposed to be a git submodule maybe or can it be removed? It at least doesn't seem useful for the source tarballs.

Regards, Daniel

**Comment by dleidert** [comment]
I may have missed the point why it is there completely. Closing myself.

**Comment by jcouball** [comment]
These are used as test fixtures. I think that the intent was that having these files in `test/files` would make this clear, but I think that the directory could be named to make this more explicit like `test/fixtures`.
