### ISSUE TITLE
Code Climate Icon No Longer Works

### ISSUE THREAD

**Issue by jcouball** [ruby-git/ruby-git#465]
In the project's main README.md, the Code Climate icon no longer loads and clicking on the icon results in a 404 error.

Here is how the icon is displayed:

[![Code Climate](https://codeclimate.com/github/ruby-git/ruby-git.png)](https://codeclimate.com/github/ruby-git/ruby-git)

The one at schacon/ruby-git still works:

[![Code Climate](https://codeclimate.com/github/schacon/ruby-git.png)](https://codeclimate.com/github/schacon/ruby-git)

**Comment by jcouball** [comment]
@perlun was the intent to move the Code Climate analysis from schacon/ruby-git to ruby-git/ruby-git?  I can't see that the latter exists.

**Comment by perlun** [comment]
Yeah, this should probably be fixed. I'll make you an admin so you can fix it yourself. :slightly_smiling_face:

**Comment by jcouball** [comment]
Fixed it by adding the ruby-git/ruby-git repository to Code Climate.  Now we just need to get the score up from "C".
