### ISSUE TITLE
Add --all option to commands like git log

### ISSUE THREAD

**Issue by jelaniwoods** [ruby-git/ruby-git#466]
As far as I can tell, there's no way to do something equivalent to `git log --all`. I use that flag consistently and it would be very nice to have it implemented in some way in this gem.

Currently:
```ruby
require "git"
g = Git.open(working_dir)
g.log                            # => only returns commits from the current branch
g.lib.log_commits(:all => true)  # => STILL only returns commits from the current branch
```

Suggested change:
```ruby
require "git"
g = Git.open(working_dir)
g.log(:all => true)
g.lib.log_commits(:all => true)
```

**Comment by sixtyfive** [comment]
I only ever get 30 log items returned by `ruby-git`. Is that because of this? If so, is there any way to quick-and-dirty-ly monkeypatch @jelaniwoods's suggestion?

**Comment by sixtyfive** [comment]
For all you weary Googlers:

```
g.log('a')
```

will give you the _whole_ log. And yes, that's very inconsistent, and one would expect it to be

```
g.log(all: true)
```

But it works.

**Comment by jcouball** [comment]
That this works at all:

```ruby
g.log('a')
```

is a bug. I plan on making it so that passing a non-integer to `Git::Base.log` will give a deprecation warning (but still work for some time) and adding this flag as @sixtyfive mentions:

```ruby
g.log(all: true)
```
