### ISSUE TITLE
Diff is not working, 8-digit hash versions

### ISSUE THREAD

**Issue by bibendi** [ruby-git/ruby-git#491]
### Subject of the issue
Describe your issue here.

### Your environment
* git: 2.20.1, ruby-git: 1.7.0
* ruby: 2.7

https://github.com/ruby-git/ruby-git/blob/1b5256cacb1c137b87be63e58253a974800d4b59/lib/git/diff.rb#L135

I have 8-digit hash versions in `@full_diff`, so above regexp is not working anymore.

```
diff --git a/db/schema.gql b/db/schema.gql
index 44eb8049..c9a46359 100644
--- a/db/schema.gql
+++ b/db/schema.gql
@@ -244,6 +244,11 @@ t
```

https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection

> it defaults to using seven characters but makes them longer if necessary to keep the SHA-1 unambiguous

**Comment by jcouball** [comment]
This was fixed in #472 which was included in version 1.8.1 of the git gem.
