### ISSUE TITLE
Published gem missing worktree.rb and worktrees.rb

### ISSUE THREAD

**Issue by kisunji** [ruby-git/ruby-git#506]
I'm not sure where is the best place to contact the maintainers, but the git ruby gem is missing files that were added in v1.8.0:

https://my.diffend.io/gems/git/1.7.0/1.8.0/

It's causing some of our CI tools to fail

**Comment by jcouball** [comment]
Thanks @hatkyinc2 I'll publish a patch release immediately.

**Comment by jcouball** [comment]
git-1.8.1 includes the fix for this issue. Apologies for the mistake. I'll add testing to our CI pipeline for this in the future.

**Comment by kisunji** [comment]
@jcouball Thanks for the quick fix!
