### ISSUE TITLE
Clone through proxy

### ISSUE THREAD

**Issue by Amnesthesia** [ruby-git/ruby-git#512]
### Your environment
* Git 2.18.4
* ruby-git 1.7.0
* ruby 2.6.0

### Steps to reproduce
No option to set proxy, setting ENV["HTTP_PROXY"] doesn't help, and `.config` options seem to not be possible to set before cloning

### Expected behaviour
Would love to be able to pass a `proxy: ""` option to `.clone`

### Actual behaviour
`execution expired`

**Comment by sbernhard** [comment]
Workaround:

        git = Git.init(dir)
        git.config('http.proxy', proxy_setting)
        git.add_remote('origin', git_url)
        git.fetch
        git.checkout(git_commit)
