### ISSUE TITLE
Add support for fetch depth

### ISSUE THREAD

**Issue by CAMOBAP** [ruby-git/ruby-git#533]
### Subject of the issue

`fetch` call doesn't support `--depth` it may be required after `git remote add`

### Your environment
* version of git and ruby-git 1.9.0
* version of ruby 2.6

### Steps to reproduce
-

### Expected behavior

Fetch call should accept `:depth`

### Actual behaviour

`fetch` call don't care about `:depth`

**Comment by jcouball** [comment]
Added in v1.10.0
