### ISSUE TITLE
[ignore] Rubygems.org account recovery verification

### ISSUE THREAD

**Issue by robertodecurnex** [ruby-git/ruby-git#542]
Rubygems.org account recovery verification

cc @sonalkr132

**Comment by sonalkr132** [comment]
Hi Roberto, I can only see a collaborator role. It should be either member or owner.

**Comment by jcouball** [comment]
What is this about?  Anything to do with ruby-git?

**Comment by robertodecurnex** [comment]
Hi @jcouball  

Sorry for the noise. Got locked out of my Rubygems account, which has publishing permissions over the gem.
It's not compromised tho.

**Comment by jcouball** [comment]
Can I help?  Do you want to publish a new version of the git gem?

I haven't been active for a while but I was planning on looking through PRs and push a new version before Christmas.

**Comment by robertodecurnex** [comment]
It's fine, thank you! 
Trying to get back to action myself, but going over a pile of hard drives looking for my recovery and gpg backup keys.
