### ISSUE TITLE
How to tell if local branch is up to date with remote branch

### ISSUE THREAD

**Issue by johncadengo** [ruby-git/ruby-git#543]
When I run `git status` in a git repo from the command line, I get a response like this:

```
$ git status

On branch main
Your branch is up to date with 'origin/main'.
```

How can I accomplish this with the gem? I don't seem to see it when I run `g.status`.

**Comment by jcouball** [comment]
If you want to know how many commit are only local vs. only remote, you can use these commands:

```Ruby
git = Git.open('.')
remote_commits_not_on_local = git.log.between('master', 'origin/master').count
local_commits_not_on_remote = git.log.between('origin/master', 'master').count
```

Would be best to to hardcode everything, but you get the idea.

**Comment by johncadengo** [comment]
Thank you @jcouball 💯
