### ISSUE TITLE
`Status#changed?` is case-sensitive despite git config

### ISSUE THREAD

**Issue by ghost** [ruby-git/ruby-git#586]
### Subject of the issue
When the git repo is configured to track files case-insensitively and a file name has a different letter case, `Status#changed?` will not report if the file has been modified.

### Your environment
* git (1.11.0)
* ruby 2.7.3

### Steps to reproduce
- init a new git repo
- (have default config `core.ignoreCase true`)
- commit `FILE`
- rename to `file`
- edit `file`
- in ruby-git, call `Status#changed?("file")`

### Expected behaviour
expected to compare tracked file case-insensitively with given filename (ie `"FILE".downcase == "file".downcase`)

### Actual behaviour
returns false

**Comment by liijunwei** [comment]
your file system coule be case insensitive

wiki: ["In filesystems in Unix-like systems, filenames are usually case-sensitive (there can be separate readme.txt and Readme.txt files in the same directory). MacOS is somewhat unusual in that, by default, it uses HFS+ and APFS in a case-insensitive"](https://en.wikipedia.org/wiki/Case_sensitivity#:~:text=In%20filesystems%20in%20Unix%2Dlike,there%20cannot%20be%20a%20readme.)

see https://github.com/pinglamb/changelog-rb/issues/12#issuecomment-1165073855 for demo

so issue might not on the gem 🤣

**Comment by nevinera** [comment]
I believe https://github.com/ruby-git/ruby-git/pull/724 will fix this (and the matching issue for `added?`, `deleted?`, and `untracked?`).

Note that the reproduction instructions should also mention that it must be performed _on a system with a case insensitive FS_ - git doesn't actually support setting `core.ignoreCase` when the filesystem is case-sensitive; you'll get confusing results from both `git` and this gem in that context.
