### ISSUE TITLE
failure using git built from source

### ISSUE THREAD

**Issue by kcburge** [ruby-git/ruby-git#604]
If git was built from source, the version appears as:

git version 2.39.**GIT**

This regex fails, producing a nil version:
https://github.com/ruby-git/ruby-git/blob/ca8ff350a63172630b8e9e919e02a0ce8e7a7a6d/lib/git/lib.rb#L1032

Fix:
      version = output[/\d+\.\d+(\.(?:GIT|\d+))+/]

This at least prevents it from failing with this error:

../.local/share/gem/ruby/3.0.0/gems/git-1.13.0/lib/git/lib.rb:1034:in `current_command_version': undefined method `split' for nil:NilClass (NoMethodError)

**Comment by jcouball** [comment]
@kcburge can you take a looks at #605 to see if it fixes this problem for you? If it does, I will merge it and make a new version of the git gem.

**Comment by kcburge** [comment]
The fix works for me.

**Comment by jcouball** [comment]
The fix is in git-1.13.1 which I published to rubygems.org yesterday.
