### ISSUE TITLE
Does this lib support git submodule operation?

### ISSUE THREAD

**Issue by ma125125t** [ruby-git/ruby-git#623]

**Comment by jcouball** [comment]
I believe it works to open a submodule with Git.open. 

Honestly, I am not so knowledgable about submodules. If you tell me what you want to be able to do, we could try it together.

**Comment by ma125125t** [comment]
> I believe it works to open a submodule with Git.open.
> 
> Honestly, I am not so knowledgable about submodules. If you tell me what you want to be able to do, we could try it together.

Git Submodule is actually another Git repository, which reads the configuration information provided in the .gitmodules file. What I actually want to do is just read and list submodule information, as well as add, delete, and modify submodule information, all of which can be achieved by modifying the .gitmodules file. Once I have obtained the submodule information, I can enter the corresponding directory and use Git-related interfaces to perform operations.

Thank you for your response.

**Comment by jcouball** [comment]
This gem will allow you to (1) open a repository and recursively checkout submodules and (2) open a submodule as a repository.

There is no functionality within this gem to list, add, delete, or modify submodules.

**Comment by jcouball** [comment]
If you have further questions about submodule functionality, please reopen this issue and ask them.
