### ISSUE TITLE
Checking out branches containing slashes broken since `1.15.0`?

### ISSUE THREAD

**Issue by alexjfisher** [ruby-git/ruby-git#647]
### Checking out branches containing slashes broken since `1.15.0`?
I'm using a project called [pdksync ](https://github.com/puppetlabs/pdksync) and [today](https://github.com/puppetlabs/pdksync/issues/177) have found that I need to pin the `git` dependency to `1.14.0` or my pipelines fail.
Looks like its failing when trying to create a commit in a new branch because the branch name contains a slash?

### Your environment
* Tested with git `2.36.4` and ruby-git `1.15.0` and `1.17.0`
* ruby 2.7

### Steps to reproduce
```ruby
require 'test_helper'
class TestRegression < Test::Unit::TestCase
  test 'this still works' do
    in_temp_dir do
      git = Git.init('.', initial_branch: 'master')
      File.write('file1.txt', 'file1')
      git.add('file1.txt')
      git.commit('commit1')
      assert_nothing_raised { git.branch('a_new_branch').checkout }
    end
  end

  test 'this does not work since 1.15.0' do
    in_temp_dir do
      git = Git.init('.', initial_branch: 'master')
      File.write('file1.txt', 'file1')
      git.add('file1.txt')
      git.commit('commit1')
      assert_nothing_raised { git.branch('foo/a_new_branch').checkout }
    end
  end
end
```

### Expected behaviour
Both tests to pass.

### Actual behaviour
The second test fails.

**Comment by alexjfisher** [comment]
My guess is that this is related to the fix for https://github.com/ruby-git/ruby-git/issues/600

**Comment by jcouball** [comment]
Thank you @alexjfisher, I will fix asap.

**Comment by jcouball** [comment]
The failing test is a big help! Thanks for that!

**Comment by jcouball** [comment]
@alexjfisher I just pushed git-1.17.2 with this fix to rubygems.org.

**Comment by alexjfisher** [comment]
@jcouball Thanks!  I've tested this, and confirm that it fixes the issue I was having with pdksync.
