### ISSUE TITLE
`cmd can not include a nested array` in 1.14.0 or higher

### ISSUE THREAD

**Issue by emmahsax** [ruby-git/ruby-git#662]
### Subject of the issue
Seeing issue with any version higher than `1.14.0`:

```
/Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/git-1.15.0/lib/git/lib.rb:1113:in `command': cmd can not include a nested array (RuntimeError)
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.23/lib/ninny/git.rb:26:in `command'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.23/lib/ninny/git.rb:78:in `track_current_branch'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.23/lib/ninny/commands/pull_request_merge.rb:47:in `check_out_branch'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.23/lib/ninny/commands/pull_request_merge.rb:27:in `execute'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.23/lib/ninny/cli.rb:41:in `stage_up'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.23/exe/ninny:15:in `<top (required)>'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/bin/ninny:25:in `load'
        from /Users/emmasax/.asdf/installs/ruby/3.0.4/bin/ninny:25:in `<main>'
```

Stacktrace is long-winded, but we've tested this on multiple versions of `git`, and consistently `1.14.0` or higher fails with the same error.

### Your environment
* version of git and ruby-git
  * git `2.40.0`
  * ruby-git `1.14.0` or higher
* version of ruby
  * ruby `3.0.4`

### Steps to reproduce

I'm using this gem through another gem, [`ninny`](https://github.com/dispatchitinc/ninny). So the best way to reproduce the same way is to take a repository on ruby `3.0.4` and ruby-git `1.14.0` or higher, and:

1. Install ninny `gem install -v 0.1.23 ninny`
1. Make a staging branch `ninny new_staging`
2. Make a merge request based off `main`/`master` with a random commit
3. Run `ninny stage_up`

### Expected behaviour
The error does not show up and the command finishes successfully.

### Actual behaviour
The error showed up and the entire command halted.

**Comment by emmahsax** [comment]
After seeing @jcouball's PR, it seems the fix is turning this
```ruby
command 'merge', ['--no-ff', "origin/#{branch_name}"]
```
to
```ruby
command('merge', '--no-ff', "origin/#{branch_name}")
```
However, it'd be nice if the error message was more explicit.

**Comment by EnginnerDog** [comment]
This mind-boggling phenomenon is like if you combine haysticks with worms you weirdo!
