### ISSUE TITLE
Setting a timeout on git subprocesses with the v2 pre-release version

### ISSUE THREAD

**Issue by gregfletch** [ruby-git/ruby-git#690]
### Subject of the issue
I am currently testing the v2 pre-release version of the gem and am particularly interested in being able to set a timeout on git subprocesses which from the sounds of https://github.com/ruby-git/ruby-git/pull/684 should be possible with the pre-release version of the gem. However, it is not clear from the documentation how one sets/passes a timeout value. For example, if I wanted to call `Git.clone`, it is not clear from the method documentation how or if it is possible to provide a timeout value. Can you clarify if this functionality is supported with v2.0.0.pre1, and if so how (looking at the method documentation for `clone`, the options hash seems to be for the options provided to the git command)?

### Your environment
* version of git: 2.43.0 and ruby-git: 2.0.0.pre1
* version of ruby: 3.3.0

### Steps to reproduce
N/A, doc improvement/clarification.

### Expected behaviour
Clarification as to whether or not support for setting timeouts is available currently with the pre-release gem version and if it is, clarification as to how timeouts are set.

### Actual behaviour
What actually happened?

**Comment by jcouball** [comment]
@gregfletch and @nckbowen (and anyone else who is interested)

I have proposed how the timeout feature would work in #692. Would appreciate your feedback. It is just the description of the implementation in an updated project README.md. Implementation will follow depending on feedback received.

**Comment by gregfletch** [comment]
LGTM, thanks for adding this so quickly @jcouball!

**Comment by rwabhinav** [comment]
@jcouball Thanks for taking up this feature. We see that the PR for adding the timeout has been merged. Would it be possible for you to release an updated new version for v2 pre-release so we can give this feature a try?

**Comment by jcouball** [comment]
@gregfletch and @rwabhinav I have just pushed git 2.0.0.pre2 to rubygems.org.

I am interested to hear your feedback.

Thanks for helping out! 🌟 ⭐
