### ISSUE TITLE
Git.open causes ArgumentError (When assigning attributes, you must pass a hash as an argument, String passed.)

### ISSUE THREAD

**Issue by RaviPatel** [ruby-git/ruby-git#707]
### Subject of the issue
Running Git.open in a rails environment throws ArgumentError (When assigning attributes, you must pass a hash as an argument, String passed.)

### Your environment
* git version 2.34.1
* ruby-git version 1.19.1
* ruby 2.7.1p83
* rails 6.1.4

### Steps to reproduce
1. I have a git directory in `/home/app/git/hello-world`
2. Run `rails c`
3. Run `require 'git'`
4. Run `Git.open('/home/app/git/hello-world')`
5. Error: `ArgumentError (When assigning attributes, you must pass a hash as an argument, String passed.)`

### Expected/Actual behaviour
When I run the same commands in IRB (i.e., not rails environment), I correctly receive the Git::Base instance. I should receive this same object in the rails environment, but I get the error instead.

**Comment by jcouball** [comment]
Can you please provide the complete error? I am not sure where the error is coming from.

Do you have a model in your rails project (or some other class) named `Git` (in the top level namespace)?

I am having trouble duplicating your environment. If you could provide a dockerfile that builds an image that can be used to demonstrate the error, that would be ideal. Or if your project is OpenSource, point me to the Github repository.

**Comment by RaviPatel** [comment]
Thanks @jcouball for your reply.
```
irb(main):007:0> puts Git.method(:open).source_location
/usr/local/rvm/gems/ruby-2.7.8/gems/git-1.19.1/lib/git.rb
380
=> nil

Yes, I do have a namespace `Git` in the project. The project is private, so I cannot share the code but I can share some snippets...
```
Gemfile:
```
gem 'git', '~> 1.19.1', require: false
```
lib/clients.rb:
```
module Clients
  def self.git
    require 'git'
    @@git_client ||= Git
  end
end
```
app/jobs/git/repository_traversing_job.rb:
```
class Git::RepositoryTraversingJob < ApplicationJob
  queue_as :git_processing

  def perform(repository_id, commit_hash_id)
    repository = Git::Repository.find(repository_id)

    git = nil
    if File.exist?(repository.working_dir)
      git = Clients.git.open(repository.working_dir, repository: repository.ssh_url, log: Logger.new(STDOUT))
    else
      git = Clients.git.clone(repository.ssh_url, repository.name, path: "/home/app/git/")
    end

  end
end
```
Both the `clone` and `open` commands return the same error:
```
irb(main):011:0> git = Clients.git.clone(repository.ssh_url, repository.name, path: "/home/app/git/")
Traceback (most recent call last):
        1: from (irb):11
ArgumentError (When assigning attributes, you must pass a hash as an argument, String passed.)
```

**Comment by jcouball** [comment]
Just to be sure, what does the following output?

```ruby
puts Clients.git.class
puts Clients.git.method(:open).source_location
```

**Comment by RaviPatel** [comment]
```
irb(main):005:0> pp Clients.git.method(:open).source_location
["/usr/local/rvm/gems/ruby-2.7.8/gems/git-1.19.1/lib/git.rb", 380]
=> ["/usr/local/rvm/gems/ruby-2.7.8/gems/git-1.19.1/lib/git.rb", 380]
irb(main):006:0> pp Clients.git.class
Module
=> Module
```

**Comment by jcouball** [comment]
If you rename your `Git` module does that make any difference?

**Comment by RaviPatel** [comment]
Yes, if I delete the Git module in my repo, the clone/open functions seem to be working. Is there a way I can keep the Git modules in my repo and still use this gem?

**Comment by jcouball** [comment]
Unfortunately, something that you or Rails is doing conflicts with the Git gem. 

Remember, when you open `Git::` and add stuff there like your own classes, you are modifying the same module that is part of the git gem.  This is the double edge sword of Ruby being able to re-open the definition of modules and classes to add new things or even change existing things.

Generally, you should create a module structure that does not open other modules and make changes to them. I would recommend a structure under `lib/` that starts with a module that is unique to your project. Otherwise, you are creating land mines for yourself that may come back to haunt you later. Something like `MyRailsProject::Git`.

I don't think this is a problem with the git gem so I am closing this issue.
