### ISSUE TITLE
Calling `.branch` on detached HEAD throws error

### ISSUE THREAD

**Issue by trevor-e** [ruby-git/ruby-git#742]
### Subject of the issue
If you get into a detached HEAD state (pretty common in CI), calling `::Git.open('.').branch` throws an error:
```
NoMethodError: undefined method `match' for nil:NilClass
from /Users/telkins/.rvm/gems/ruby-3.2.2/gems/git-2.2.0/lib/git/branch.rb:137:in `parse_name'
```

### Your environment
* version of git and ruby-git: 2.44.0 and 2.2.0
* version of ruby: 3.2.2

### Steps to reproduce
- Get into a detached HEAD state. The easiest way is to checkout an individual commit on a branch.
- Run `::Git.open('.').branch` and see it throws an error

### Expected behaviour
- It should return `HEAD` as the branch name

### Actual behaviour
- It throws a `NoMethodError` because the regex fails

**Comment by jcouball** [comment]
This was fixed in git-2.3.0.
