### ISSUE TITLE
Suggestion: Enhancing error messages for clarity.

### ISSUE THREAD

**Issue by ndregs** [ruby-git/ruby-git#761]
While reviewing the code, I noticed the following:

- Enhancing error messages for clarity.

This could be improved to enhance the project quality. Let me know your thoughts!

**Comment by jcouball** [comment]
Hello @ndregs, thank you for your interest in this project.

Can you please do one of the following:

* List specifics in this issue so someone can pick up the issue and create a PR
OR
* Submit a PR with the changes you recommend

Currently, these issues are not actionable.

**Comment by jcouball** [comment]
Your suggestions are welcome. Please either reopen with the specific suggestions or (even better) submit a PR with your suggestion for review.
