### ISSUE TITLE
Suggestion: Improving variable naming for better readability.

### ISSUE THREAD

**Issue by ndregs** [ruby-git/ruby-git#762]
While reviewing the code, I noticed the following:

- Improving variable naming for better readability.

This could be improved to enhance the project quality. Let me know your thoughts!

**Comment by jcouball** [comment]
What do you have in mind? You could express this with a PR.

If there is something misnamed that could cause confusion, I am in favor of such a change.

**Comment by jcouball** [comment]
Hello @ndregs, thank you for your interest in this project.

Can you please do one of the following:

* List specifics in this issue so someone can pick up the issue and create a PR
OR
* Submit a PR with the changes you recommend

Currently, these issues are not actionable.

**Comment by jcouball** [comment]
Your suggestions are welcome. Please either reopen with the specific suggestions or (even better) submit a PR with your suggestion for review.
