### ISSUE TITLE
possible memory leak when calling status

### ISSUE THREAD

**Issue by Sujimichi** [ruby-git/ruby-git#92]
I've been trying to find a memory leak in a rails app that I'm making.  A particular request is increasing the apps memory usage with each request.  I stripped everything out of the controller and view for that request and observed that the apps memory usage was now static when it was called.   Then line by line I added the controller and view code back in.  
The point at which the memory usage started increasing again was a call to a method which in turn called .status on a repo.  With everything removed except the call to repo.status the memory usage was still increasing.  Without out the call to repo.status the memory usage stayed constant.

I did a simple test in a fresh irb.  Connected to a repo and called status and observed the consoles memory usage.

``` ruby
git = Git.open(<path_to_repo>)
git.status
```

each time I called git.status I could see the consoles mem usage increase by around 80kb.  If I stopped calling git.status the mem usage stayed constant.
I found this to be the case on both Linux and Windows dev machines.

I'm sorry if I'm barking up the wrong tree with this, I hope I'm not wasting your time!

**Comment by costa** [comment]
I have reasons to believe that @Sujimichi might have been on to something.

@robertodecurnex May I ask how you checked this? Have you seen any servers that use this gem (within a main process)? Have you tried running `status` on a large repo, like, 1000 times in a loop?

I'm having memory problems with a very simple server that uses this gem and my checks show unreasonable memory consumption.

**Comment by costa** [comment]
cc @jcouball
